language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "rbx-19mode"
gemfile:
  - "gemfiles/rails_3.1.gemfile"
  - "gemfiles/rails_3.2.gemfile"
  - "gemfiles/rails_4.0.gemfile"
script: bundle exec rspec spec/examples
bundler_args: --without=debug
before_install:
  - sudo sh -c "echo 'JVM_OPTS=\"\${JVM_OPTS} -Djava.net.preferIPv4Stack=false\"' >> /usr/local/cassandra/conf/cassandra-env.sh"
  - test -f "/usr/local/cassandra/etc/cassandra-env.sh" && sudo rm -f /usr/local/cassandra/conf/cassandra-env.sh && sudo ln -s /usr/local/cassandra/etc/cassandra-env.sh /usr/local/cassandra/conf/cassandra-env.sh
  - sudo service cassandra start
  - sleep 3
after_failure: 'ls /var/log/cassandra; tail -n 100 /var/log/cassandra/system.log'
